name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]
        os: [ubuntu-latest, windows-latest]
        cmd: [npm it]
        exclude: # only test windows on node 12
          - os: windows-latest
            node: 8.x
          - os: windows-latest
            node: 10.x
          - os: windows-latest
            node: 12.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: ${{ matrix.cmd }}
      run: ${{ matrix.cmd }}
